<a href="https://colab.research.google.com/github/rishika-p/assignment-3/blob/master/a_3(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a=np.array([[1,0],[0,1]])
b=np.array([[1, 2], [3, 4]])
print("Original matrix : ")
print(p)
print(q)
print("Outer product:")
result=np.outer(p,q)
print(result)

Original matrix : 
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]
